import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import HomeInfo from "../components/HomeInfo";
import HomeDisplay from "../components/HomeDisplay";
import Footer from "../components/Footer";


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>ACES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Navbar */}
      
      <div className="relative h-1/3">
        <div className="">

        <Image src="https://cdn.pixabay.com/photo/2016/10/11/21/43/geometric-1732847_960_720.jpg" alt="image" 
        layout="fill" objectFit="" className=""/>
        </div>
        <Header/>
        <HomeInfo/>
      </div>

      
      <HomeDisplay/>
      
      
      
      {/*Main*/}
      {/*Footer*/}
      <Footer/>
      
    </div>
  );
}
